apiVersion: apps/v1
kind: Deployment
metadata:
  name: 2048-game
  namespace: 2048-game
spec:
  replicas: 3  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: 2048-game
          image: jithendar/2048:latest  # Use your actual Docker image name and tag
          ports:
            - containerPort: 3000  # The port your React app is listening on

---
apiVersion: v1
kind: Service
metadata:
  name: 2048-game
spec:
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 80  # The port exposed by the service within the cluster
      targetPort: 3000  # The port your React app is listening on inside the pod
  type: LoadBalancer

